### ISSUE TITLE
Bug: Adaptor not working correctly on Windows CMF

### ISSUE THREAD

**Issue by yuanmich2** [aws-deadline/deadline-cloud-for-after-effects#30]
### Expected Behaviour

I should be able to install python, install the aws cli, run pip install deadline deadline-cloud-for-after-effects deadline-cloud-worker-agent, and run the install-deadline-worker command to set up my worker.

### Current Behaviour

When I first set up my worker and ran a job, I was hit with this error:

```
2024/05/03 13:46:36-07:00 C:\ProgramData\Amazon\OpenJD\session-7703d39d3c31476e87a0691ecfbf6ba7y10ru5nk>afterfx-openjd daemon start --connection-file C:\ProgramData\Amazon\OpenJD\session-7703d39d3c31476e87a0691ecfbf6ba7y10ru5nk/connection.json --init-data file://C:\ProgramData\Amazon\OpenJD\session-7703d39d3c31476e87a0691ecfbf6ba7y10ru5nk\embedded_filesy89in_x0\init-data.yaml  
2024/05/03 13:46:36-07:00 Traceback (most recent call last):
2024/05/03 13:46:36-07:00   File "<frozen runpy>", line 198, in _run_module_as_main
2024/05/03 13:46:36-07:00   File "<frozen runpy>", line 88, in _run_code
2024/05/03 13:46:36-07:00   File "C:\Program Files\Python311\Scripts\afterfx-openjd.exe\__main__.py", line 4, in <module>
2024/05/03 13:46:36-07:00 ModuleNotFoundError: No module named 'deadline.ae_adaptor'
```

I found a folder called ae_adaptor at C:\Program Files\Python311\Lib\site-packages which seemed like the wrong directory, so I moved it to C:\Program Files\Python311\Lib\site-packages\deadline

then I got this error:
```
2024/05/03 13:49:45-07:00 INFO: Running command: python "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_client.py"
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 STDERR: Traceback (most recent call last):
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 STDERR:   File "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_client.py", line 111, in <module>
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 STDERR:     main()
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 STDERR:   File "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_client.py", line 105, in main
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 STDERR:     client = AEClient(server_path)
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 STDERR:              ^^^^^^^^^^^^^^^^^^^^^
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 STDERR:   File "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_client.py", line 40, in __init__
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 STDERR:     client_path_abs = os.path.abspath(os.path.normpath(self.ae_client_path))
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 STDERR:                                                        ^^^^^^^^^^^^^^^^^^^
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 STDERR:   File "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_client.py", line 81, in ae_client_path
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 STDERR:     raise FileNotFoundError(
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 STDERR: FileNotFoundError: Could not find ipc.jsx . Check that the AEClient package is in one of the following directories: ['C:\\Program Files\\Python311\\Lib\\site-packages\\openjd', 'C:\\Program Files\\Python311\\Lib\\site-packages\\deadline', 'C:\\Program Files\\Python311\\python311.zip', 'C:\\Program Files\\Python311\\DLLs', 'C:\\Program Files\\Python311\\Lib', 'C:\\Program Files\\Python311', 'C:\\Program Files\\Python311\\Lib\\site-packages', 'C:\\Program Files\\Python311\\Lib\\site-packages\\win32', 'C:\\Program Files\\Python311\\Lib\\site-packages\\win32\\lib', 'C:\\Program Files\\Python311\\Lib\\site-packages\\Pythonwin']
2024/05/03 13:49:45-07:00  
2024/05/03 13:49:45-07:00 openjd_fail: Error encountered while starting adaptor: After Effects encountered an error and was not able to complete initialization actions.
```

I searched my PC for ipc.jsx and found that it only existed in the github repo in the src/aeipc folder.

The few lines surround line 81, the one that threw the error looks like this:
```
        for dir_ in sys.path:
            path = os.path.join(dir_, "ae_adaptor", "clientipc", "ipc.jsx")
            if os.path.isfile(path):
                return path
        raise FileNotFoundError(
            f"Could not find ipc.jsx . Check that the AEClient package is in one of the following directories: "
            f"{sys.path[1:]}"
        )
```
which makes it clear that the adaptor is expecting to find ipc.jsx in /system/path/ae_adaptor/clientipc/ipc.jsx, but no such file existed.

I uninstalled and reinstalled the deadline-cloud-for-after-effects package to see if it was a fluke, but the folder never appeared, so I manually copied the aeipc folder into my ae_adaptor folder and renamed it to "clientipc" to match what the adaptor was looking for.

then I ran into this issue:
```
2024/05/03 14:15:40-07:00 ADAPTOR_OUTPUT: INFO: Running command: python "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_client.py"
2024/05/03 14:15:40-07:00 ADAPTOR_OUTPUT: STDOUT: Starting AfterFX: ['afterfx', '-s', "var x = new File('C:\\\\Program Files\\\\Python311\\\\Lib\\\\site-packages\\\\deadline\\\\ae_adaptor\\\\clientipc\\\\ipc.jsx') ; x.open(); eval(x.read()); app.exitAfterLaunchAndEval = false;"]
2024/05/03 14:15:55-07:00 ADAPTOR_OUTPUT: STDOUT: Performing action: {"name": "project_file", "args": {"project_file": "C:\\ProgramData\\Amazon\\OpenJD\\session-9f662f1436fc452fa0af7f351c276e65xqo1rs06\\assetroot-0a339ba0c0ce03618ff1\\Desktop\\TestProject.aep"}}
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR: Traceback (most recent call last):
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:   File "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_client.py", line 111, in <module>
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:     main()
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:   File "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_client.py", line 106, in main
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:     client.poll()
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:   File "C:\Program Files\Python311\Lib\site-packages\openjd\adaptor_runtime_client\base_client_interface.py", line 212, in poll
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:     self._perform_action(action)
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:   File "C:\Program Files\Python311\Lib\site-packages\openjd\adaptor_runtime_client\base_client_interface.py", line 233, in _perform_action
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:     action_func(a.args)
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:   File "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_handler.py", line 150, in set_project_file
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:     resp = send_command("open_project", data)
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:   File "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ipc.py", line 25, in send_command
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR:     s.connect((host, port))
2024/05/03 14:15:56-07:00 ADAPTOR_OUTPUT: STDERR: ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
2024/05/03 14:15:58-07:00 ADAPTOR_OUTPUT: STDERR: [2024-05-03 21:15:58] [info] asio async_connect error: asio.system:10061 (No connection could be made because the target machine actively refused it.)
2024/05/03 14:15:58-07:00 ADAPTOR_OUTPUT: STDERR: [2024-05-03 21:15:58] [info] Error getting remote endpoint: asio.system:10057 (A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.)
2024/05/03 14:15:58-07:00 ADAPTOR_OUTPUT: STDERR: [2024-05-03 21:15:58] [error] handle_connect error: No connection could be made because the target machine actively refused it.
```

I double-checked that After Effects had the "Allow Scripts to write files and access the network" option enabled and then attempted to start AfterFX manually with the following command: afterfx -s "var x = new File('C:\\\\Program Files\\\\Python311\\\\Lib\\\\site-packages\\\\deadline\\\\ae_adaptor\\\\clientipc\\\\ipc.jsx') ; x.open(); eval(x.read()); app.exitAfterLaunchAndEval = false;"

I got the same error. However, if I first opened a project in the After Effects GUI and then ran the command it succeeded and I was able to confirm that After Effects was listening on the correct port through resource monitor.

Still not able to produce a render though

### Reproduction Steps

I created a Windows 2019 EC2. I installed the aws cli, python, and all relevant python packages. I set up the worker agent with my farm and attempted to render something.

### Code Snippet

n/a

**Comment by epmog** [comment]
For the first issue, it appears as though ae is not set-up to go to the deadline namespace by default. Should be relatively easy to fix.

For the second issue, there's some instructions in https://github.com/aws-deadline/deadline-cloud-for-after-effects/blob/mainline/docs/adaptor_ipc.md that indicate how the ipc.jsx gets generated. I believe we should make this in the build as well to make it work out of the box

**Comment by yuanmich2** [comment]
I just ran through the steps to regenerate ipc.jsx and a quick diff showed that it changed the file a lot. I think it just copied all the imports into the same file.

I now get this error ~~which I think is progress~~

```
2024/05/03 15:02:46-07:00 ADAPTOR_OUTPUT: INFO: Running command: python "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_client.py"
2024/05/03 15:02:46-07:00 ADAPTOR_OUTPUT: STDOUT: Starting AfterFX: ['afterfx', '-s', "var x = new File('C:\\\\Program Files\\\\Python311\\\\Lib\\\\site-packages\\\\deadline\\\\ae_adaptor\\\\clientipc\\\\ipc.jsx') ; x.open(); eval(x.read()); app.exitAfterLaunchAndEval = false;"]
2024/05/03 15:03:01-07:00 ADAPTOR_OUTPUT: STDOUT: Performing action: {"name": "project_file", "args": {"project_file": "C:\\ProgramData\\Amazon\\OpenJD\\session-dc21f20bde26492cb3b7a097e8072167w93z1qy0\\assetroot-0a339ba0c0ce03618ff1\\Desktop\\TestProject.aep"}}
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR: Traceback (most recent call last):
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:   File "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_client.py", line 111, in <module>
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:     main()
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:   File "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_client.py", line 106, in main
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:     client.poll()
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:   File "C:\Program Files\Python311\Lib\site-packages\openjd\adaptor_runtime_client\base_client_interface.py", line 212, in poll
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:     self._perform_action(action)
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:   File "C:\Program Files\Python311\Lib\site-packages\openjd\adaptor_runtime_client\base_client_interface.py", line 233, in _perform_action
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:     action_func(a.args)
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:   File "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_handler.py", line 150, in set_project_file
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:     resp = send_command("open_project", data)
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:   File "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ipc.py", line 26, in send_command
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:     response = s.recv(4096)
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR:                ^^^^^^^^^^^^
2024/05/03 15:04:56-07:00 ADAPTOR_OUTPUT: STDERR: ConnectionResetError: [WinError 10054] An existing connection was forcibly closed by the remote host
```

EDIT:
Just ran the job a couple more times and I'm back to getting the original `ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it` error

So no progress yet.

**Comment by epmog** [comment]
Ah, my bad. I didn't read far enough.

For the third issue, it looks like it expects afterfx to already be running, as when I look at the documentation, https://helpx.adobe.com/after-effects/using/scripts.html, I see that it doesn't start a new instance of afterfx.

That shouldn't be too much of a problem to add to the adaptor either if needed. Seems like `-noui` may also alleviate this issue.

**Comment by yuanmich2** [comment]
Just as an update. I am still unable to render.
When I edit the scripts to add the -noui flag, an instance of AfterFX opens and begins listening to port 8008, but it still doesn't seem to be accepting the commands to open and render the project.

Latest errors look like this:
```
2024/05/06 10:36:25-07:00 ADAPTOR_OUTPUT: INFO: Running in background daemon mode.
2024/05/06 10:36:25-07:00 ADAPTOR_OUTPUT: INFO: Creating Named Pipe with name: \\.\pipe\AdaptorNamedPipe_316
2024/05/06 10:36:25-07:00 ADAPTOR_OUTPUT: INFO: Loading 'init_data' schema from C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEAdaptor\schemas\init_data.schema.json
2024/05/06 10:36:25-07:00 ADAPTOR_OUTPUT: INFO: Loading 'run_data' schema from C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEAdaptor\schemas\run_data.schema.json
2024/05/06 10:36:25-07:00 ADAPTOR_OUTPUT: DEBUG: start after effects server thread
2024/05/06 10:36:25-07:00 ADAPTOR_OUTPUT: DEBUG: start ae server
2024/05/06 10:36:25-07:00 ADAPTOR_OUTPUT: INFO: Creating Named Pipe with name: \\.\pipe\AdaptorServerNamedPipe_316
2024/05/06 10:36:26-07:00 ADAPTOR_OUTPUT: DEBUG: ____action made for project_file_______
2024/05/06 10:36:26-07:00 ADAPTOR_OUTPUT: DEBUG: ____action made for comp_name_______
2024/05/06 10:36:26-07:00 ADAPTOR_OUTPUT: DEBUG: ____action made for output_file_path_______
2024/05/06 10:36:26-07:00 ADAPTOR_OUTPUT: DEBUG: ____action made for output_pattern_______
2024/05/06 10:36:26-07:00 ADAPTOR_OUTPUT: DEBUG: ____action made for output_format_______
2024/05/06 10:36:26-07:00 ADAPTOR_OUTPUT: INFO: Running command: python "C:\Program Files\Python311\Lib\site-packages\deadline\ae_adaptor\AEClient\ae_client.py"
2024/05/06 10:36:26-07:00 ADAPTOR_OUTPUT: STDOUT: Starting AfterFX: ['afterfx', '-noui', '-s', "var x = new File('C:\\\\Program Files\\\\Python311\\\\Lib\\\\site-packages\\\\deadline\\\\ae_adaptor\\\\clientipc\\\\ipc.jsx') ; x.open(); eval(x.read()); app.exitAfterLaunchAndEval = false;"]
2024/05/06 10:36:30-07:00 ADAPTOR_OUTPUT: STDERR: [12584][Warn] [general] We are going to deprecate hostInfo access soon. Please use HostInfoController instead.
2024/05/06 10:36:30-07:00 ADAPTOR_OUTPUT: STDERR: [2024-05-06 17:36:29] [info] asio async_connect error: asio.system:10061 (No connection could be made because the target machine actively refused it.)
2024/05/06 10:36:30-07:00 ADAPTOR_OUTPUT: STDERR: [2024-05-06 17:36:29] [info] Error getting remote endpoint: asio.system:10057 (A request to send or receive data was disallowed because the socket is not connected and (when sending on a datagram socket using a sendto call) no address was supplied.)
2024/05/06 10:36:30-07:00 ADAPTOR_OUTPUT: STDERR: [2024-05-06 17:36:29] [error] handle_connect error: No connection could be made because the target machine actively refused it.
2024/05/06 10:36:41-07:00 ADAPTOR_OUTPUT: STDOUT: Performing action: {"name": "project_file", "args": {"project_file": "C:\\ProgramData\\Amazon\\OpenJD\\session-c7fb6881889442769670bbebf1aafc157xwod4r_\\assetroot-0a339ba0c0ce03618ff1\\Desktop\\TestProject.aep"}}
```

after printing this out, the job will hang indefinitely.

**Comment by mg-aws** [comment]
same here, same setup as yuanmich2 reported in OP. To trigger issue, just manually call it:

```
PS C:\Program Files\Python312\Scripts> afterfx-openjd --help
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Program Files\Python312\Scripts\afterfx-openjd.exe\__main__.py", line 4, in <module>
ModuleNotFoundError: No module named 'deadline.ae_adaptor'
```
Using:
- deadline-cloud-for-after-effects v1.16.0
- Microsoft Windows Server 2022 Datacenter 10.0.20348 N/A Build 20348
- python 3.12.3

**Comment by yuanmich2** [comment]
I actually found the fix to that specific error and shared it in my original post:

> I found a folder called ae_adaptor at C:\Program Files\Python311\Lib\site-packages which seemed like the wrong directory, so I moved it to C:\Program Files\Python311\Lib\site-packages\deadline

**Comment by yuanmich2** [comment]
One of the later releases fixed this issue
